### ISSUE TITLE
native-or-bluebird is deprecated. please switch to any-promise

### ISSUE THREAD

**Issue by jonathanong** [greim/ugly-adapter#2]
https://github.com/kevinbeaty/any-promise

this implementation supports more promise implementations and allows the end-user to configure the promise implementation.

**Comment by greim** [comment]
Thanks.

**Comment by kevinbeaty** [comment]
FYI: Just published `any-promise` version 1.0.0  (no API changes, just time for v1).  May want to update your deps to "^1.0.0".

**Comment by greim** [comment]
Done and done. Thanks.
